### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by sebastianpisula** [akiran/gulp-sassbeautify#2]
```
var sassbeautify = require('gulp-sassbeautify');

gulp.task('beautify-scss', function () {
    gulp.src('src/**/*.scss')
        .pipe(sassbeautify())
        .pipe(gulp.dest('src'))
});
```

> [14:09:11] Starting 'beautify-scss'...
> [14:09:11] Finished 'beautify-scss' after 11 ms
> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn sass-convert ENOENT
>     at exports._errnoException (util.js:890:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
>     at onErrorNT (internal/child_process.js:348:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jonnykates** [comment]
I'm getting this too.
node 8.9.3
npm 5.5.1
